Fix multiple blocks from itp
marrink-lab/polyply_1.0 pull request #155
Opened 2021-09-22 15:10 UTC by fgrunewald

Small bug, big effect. Now we can also deal with multiple blocks from itp files.

2021-09-23 13:15 UTC, pckroon requested changes
Code /looks/ ok, but I can't see what's going on, and what kind of effect this change has. Could you write a paragraph on what happened before, and what happens now?

Also, tests are missing.

2021-09-23 14:13 UTC, fgrunewald commented
Very simple bug: What should happen is that every time a fragment is newly added to the meta-molecule the if is triggerd. We check this by seeing if a node is in 'added_fragment_nodes'. When the current node is not in added_fragment_nodes then we know that we have to add the fragment details. But instead of looking into added_fragment_nodes it was checking added_fragments, which never gets updated or changed anywhere in the code. Basically it's just dangling. I assume this was a spelling mistake. But it only becomes and issue if you're adding more than 2 fragments from itp file.

2021-09-24 07:48 UTC, pckroon commented
Ok, makes sense. The comments could be extended a bit, but that's optional. 
Once there's a test it's good to go!

2021-09-27 11:51 UTC, pckroon approved these changes

2021-09-27 12:44 UTC, merged