Add/pdms
marrink-lab/polyply_1.0 pull request #290
Opened 2022-12-14 14:21 UTC by fgrunewald

2023-02-07 15:03 UTC, fgrunewald commented
@ricalessandri can you do a small spell check on line 37 and 75ff of PDMS.martini3.ff

Otherwise this one should be good to go

2023-02-07 15:23 UTC, ricalessandri commented
Ok. Will do it later today.

2023-02-08 04:45 UTC, ricalessandri commented on polyply/data/martini3/PDMS.martini3.ff
> +Parameters for this model are custom and available for download here: https://github.com/marrink-lab/martini-forcefields/blob/main/martini_forcefields/regular/v3.0.0/gmx_files_contributed/DMS_martini
```suggestion
Parameters for this model are custom and available for download at: https://github.com/marrink-lab/martini-forcefields/blob/main/martini_forcefields/regular/v3.0.0/gmx_files_contributed/DMS_martini3_v1.itp
```

2023-02-08 04:45 UTC, ricalessandri commented on polyply/data/martini3/PDMS.martini3.ff
> +You should patch PDMS with a terminal residue. Use -seq PDMSter:1 PPE:4 PDMSter:1
```suggestion
You should patch PDMS with a terminal residue. Use -seq PDMSter:1 PDMS:4 PDMSter:1
```

2023-02-08 04:46 UTC, ricalessandri commented on polyply/data/martini3/PDMS.martini3.ff
> +You should patch PDMS with a terminal residue. Use -seq PDMSter:1 PPE:4 PDMSter:1
```suggestion
You should patch PDMS with a terminal residue. Use -seq PDMSter:1 PDMS:4 PDMSter:1
```

2023-02-08 04:47 UTC, ricalessandri commented on polyply/data/martini3/PDMS.martini3.ff
> +You should patch PDMS with a terminal residue. Use -seq PDMSter:1 PPE:4 PDMSter:1
Another thing is, "4" is a bit arbitrary there of course but I guess this should be clear enough

2023-02-08 04:47 UTC, ricalessandri commented on polyply/data/martini3/PDMS.martini3.ff
> +You should patch PDMS with a terminal residue. Use -seq PDMSter:1 PPE:4 PDMSter:1
Another thing is, "4" is a bit arbitrary there of course but I guess this should be clear enough

2023-02-08 04:48 UTC, ricalessandri commented on LIBRARY.md
> +|PDMS                           |DMS                      |                                                                       |[martini3](polyply/data/martini3/PDMS.martini3.ff)
```suggestion
|polydimethylsiloxane                           |PDMS                      |                                                                       |[martini3](polyply/data/martini3/PDMS.martini3.ff)
```

2023-02-08 04:51 UTC, ricalessandri requested changes
Some small fixes, some are a bit subjective so feel free to accept/reject.
I also already commited a fix to LIBRARY.md

2023-02-08 16:09 UTC, fgrunewald commented
@ricalessandri thanks for catching the typos and copy errors

2023-02-08 16:20 UTC, ricalessandri approved these changes
No problem!

2023-02-08 16:51 UTC, merged