Fix/305
marrink-lab/polyply_1.0 pull request #306
Opened 2023-03-09 14:05 UTC by fgrunewald

2023-04-04 08:34 UTC, fgrunewald commented
@pckroon this PR covers the few lines which accidentally made it into the other. Since you already read them could your review this as well? :laughing:

2023-04-04 10:09 UTC, pckroon requested changes
Small nitpick, fine otherwise

2023-04-04 10:09 UTC, pckroon commented on polyply/src/map_to_molecule.py
> +           # in this case we have to add the node from the block definitions
This is a bad change

2023-04-12 14:53 UTC, pckroon approved these changes

2023-04-12 14:57 UTC, merged