Implementation of MC bending sampling
marrink-lab/polyply_1.0 pull request #344
Opened 2023-09-24 12:48 UTC by fgrunewald

2023-09-28 11:19 UTC, fgrunewald commented
some observation:

stiff polymers where `contour-length >~ lp` need a low number of rewind steps (e.g. setting `-rw 1`). For single polymers this helps to get relatively straight chain conformations.

2023-10-19 12:29 UTC, fgrunewald commented
summoning @pckroon for a technical code review

2023-10-19 14:15 UTC, pckroon requested changes
Some small comments, mostly superficial

2023-10-19 14:15 UTC, pckroon commented on polyply/src/random_walk.py
> +            print(step_count)
Leftover

2023-10-19 14:15 UTC, pckroon commented on polyply/tests/test_nb_engine.py
> +    assert np.isclose(prob, ref_prob, atol=10**-5)
```suggestion
    assert prob == pytest.approx(ref_prob, abs=10**-5)
```

2023-10-19 14:15 UTC, pckroon commented on polyply/tests/test_random_walk.py
> +     ),
I'd prefer each of these cases on 1 line

2023-10-20 18:56 UTC, fgrunewald commented on polyply/src/nonbond_engine.py
> +            bending constant
nope it's unitless; it's not like a physically meaningful constant but rather if it's low the polymer if flexible if it's high it's stiff. The actual bending is also determined by the volume and force exclusion criteria used in the RW

2023-10-20 18:57 UTC, fgrunewald commented on polyply/src/nonbond_engine.py
> +        prob = np.exp(lp*ang_val/180)/(180*(np.exp(lp)-1)/lp)
the denominator is the normalisation, which is why it is written a bit funny; I'll put a comment there and keep it.

2023-11-10 10:35 UTC, fgrunewald commented on polyply/src/random_walk.py
> +                if prob > test_prob:
Yes, they are. In the first case, we test if the new state is more likely than the previous one. If yes, we accept it right away, and if not we test if the state is more likely than a randomly pulled probability from a uniform distribution.

2023-11-12 21:17 UTC, fgrunewald commented on bin/polyply
> +                                         'the higher the more straight the chain.'))
remove this option

2023-11-16 10:21 UTC, pckroon submitted a review, later dismissed
LGTM, assuming you addressed all my previous comments

2023-11-21 11:46 UTC, pckroon approved these changes

2023-11-21 11:53 UTC, merged