Cgsmiles 1
marrink-lab/polyply_1.0 pull request #377
Opened 2024-07-03 14:58 UTC by fgrunewald

Adding CGSmiles strings as option to describe polymer graphs. 

This PR needs to wait until the CGSmiles package is advanced a little more but in principle works.

2024-07-18 10:04 UTC, pckroon requested changes

2024-07-18 10:04 UTC, pckroon commented on polyply/src/meta_molecule.py
> +                    meta_graph.nodes['graph'].nodes[atom]['resname'] = resname
resname is undefined here

2024-07-18 10:04 UTC, pckroon commented on polyply/src/simple_seq_parsers.py
> +            string of residues format name:number
```suggestion
    sequence: list[str]
            string of residues format name:number
```

2025-07-02 06:22 UTC, fgrunewald commented on polyply/src/gen_itp.py
> +               dsdna=False, mods=[], protter=False):
done

2025-07-08 13:54 UTC, merged