Add [10.1021/jacsau.4c00276]  polymers to the polyply library
marrink-lab/polyply_1.0 pull request #378
Opened 2024-07-06 13:30 UTC by ricalessandri

Contributing the 3x phthalimide-containing polymer models developed in [here](https://doi.org/10.1021/jacsau.4c00276) to the polyply library.

2024-07-08 08:42 UTC, fgrunewald requested changes
Ideally we would only have one CH3ter and change the charges or atomtype once it get's connected via a different residue / bond. Do you think that would be possible?

2024-07-08 10:43 UTC, ricalessandri commented
Right, that makes sense. Does https://github.com/marrink-lab/polyply_1.0/pull/327 handle this automagically? My itp_to_ff version does not. I could do it by hand for these 3 polymers.

2024-07-08 10:50 UTC, fgrunewald commented
@ricalessandri yes, but there are some edge cases I haven't considered yet. For example, when CH3 is bound to acrylate either via the backbone or via the oxygen.

2025-03-24 06:34 UTC, fgrunewald commented
@ricalessandri is this ready to be merged?

2025-03-26 00:17 UTC, ricalessandri commented
In [25f992e](https://github.com/marrink-lab/polyply_1.0/pull/378/commits/25f992e1c101c1d2b29c468694c00c60f67436b6), I'm trying the approach of a unique `CH3.ff`. First off, I tried to to this for PTMA (for that, I actually currently define `CH3a` and `CH3b`, whose difference is just charges). If this works, then I can do the same for the new redox polymers and then this PR is done. However, the test is failing? Can you take a quick look to check what I'm doing wrong, @fgrunewald ?

2025-03-26 08:24 UTC, fgrunewald commented on polyply/data/oplsaaLigParGen/links_PTMA.ff
> +  -H4  {"replace": {"charge":  0.0386}}
@ricalessandri I think you would want to have these as +C1 and +H2 etc. Now they are referring to the previous residue, which I think is incorrect.

2025-03-26 21:55 UTC, ricalessandri commented on polyply/data/oplsaaLigParGen/links_PTMA.ff
> +  -H4  {"replace": {"charge":  0.0386}}
yes, indeed

2025-03-26 23:03 UTC, ricalessandri commented
Nice, test for PTMA passed. What I had to do:

1. Fix what @fgrunewald suggested.
2. Fix some other problem I found. Namely, the previous version of the CH3b link .ff file actually contained a mistake that, _for some reason I don't fully understand_, was not showing up in the output itp file. But now that I made a single CH3.ff, it was showing up, namely, there were 2 times the internal angles of the CH3 block "on the right". So 3 extra lines in the final .itp file that were making the test still fail after I fixed point 1.

Final note: I've fixed the LIBRARY.md conflict following the format I suggest in https://github.com/marrink-lab/polyply_1.0/pull/411.

2025-03-27 22:39 UTC, ricalessandri commented
PR should be ready to be merged now @fgrunewald !

2025-03-28 06:58 UTC, fgrunewald approved these changes

2025-03-28 06:58 UTC, merged